### PR TITLE
Add WordCamp Colombo

### PR DESCRIPTION
**Pull request by iamchathu**

### CODE REVIEW

**Comment by ryanlanciaux** [comment]
Awesome thank you! :+1:

**Comment by iamchathu** [comment]
No worries. How about scaling. It seems now list growing.May be a way like 2017.08.json, 2017.09.json would reduce it. Any suggestions?

**Comment by ryanlanciaux** [comment]
Yea - good thinking :smile: 

I am hoping to do something more sophisticated when there are more future events listed. I think something inline with what you are suggesting where there will be an "upcoming" list of events AND an archived list of events by year. At that point, when you load the site, it'll only show upcoming events by default and "All" will switch to "Archive." This archive view would also show a dropdown for year and depending on which year was selected would load a different json file.

If that gets unwieldy I would love to switch to something like [up-for-grabs.net](https://github.com/up-for-grabs/up-for-grabs.net/tree/gh-pages/_data/projects) (but still using json rather than yml)

I really appreciate this :+1:

**Comment by iamchathu** [comment]
I love JSON too. Happy to see your suggestion. It is great. I will contribute to this as I can. 👍

**Pull request merged**
